Create CONTRIBUTING.md
conjurinc/summon-conjur pull request #50
Opened 2020-03-12 12:23 UTC by doodlesbykumbi

Linked to cyberark/community#30

2020-03-12 13:26 UTC, hughsaunders submitted a review, later dismissed

2020-03-12 18:39 UTC, izgeri requested changes
Can you please move the `## Development` section from the README to CONTRIBUTING?

2020-03-13 12:06 UTC, doodlesbykumbi commented
@izgeri Done

2020-03-13 16:33 UTC, izgeri approved these changes

2020-03-13 16:33 UTC, merged